algoritmo "parouimpar"
// Função : Descobrir se o número é par ou ímpar
// Autor : Arthur Augusto
// Data : 13/07/2020
// Seção de Declarações 
var
numero, total: inteiro

inicio

//Entrada
escreval("Escolha um número: ")
leia(numero)

//Processamento
total<- (numero mod 2)
Escolha total
   caso 1
      escreval("Esse número é ímpar!")
   caso 0
      escreval("Esse número é par!")
fimescolha



fimalgoritmo
